README.md, defaults/main.yml, tasks/main.yml
The role already supported a default variable ("network_provider") and
host variables ("network_provider_default", "network_service_name",
"network_packages").
Don't use nested variables under "network" like
network:
provider:
ignore_error:
connections:
instead promote them all to top-level variables like:
network_provider:
network_ignore_error:
network_connections:
This seems more consistent (as we already have multiple top-level
variables), it seems to follow ansible style, and it makes it easier
to overload individual variables via conditional include files.
=> network: use top-level variables instead of nested "network" variable

library/network_connections.py, tests/test_network_connections.py
This fixes a bug in the `network_connections` module when using the `initscripts` provider and encountering a connection with `autoconnect `set to false. It fails to write any `ONBOOT=` line to the interface's `ifcfg-*` file, which RHEL treats as equivalent to `ONBOOT=yes`.
This explicitly sets `ONBOOT` for all interfaces defined, instead of relying on what RHEL considers its default value.
=> Fix handling of autoconnect parameter

defaults/main.yml, tests/tasks/assert-profile_absent.yml, tests/tasks/assert-profile_present.yml, tests/tests_bridge.yml, tests/tests_bridge_initscripts.yml
This contains the working part of the tests from #53 to get this merged to benefit from the tests already. It also fixes #68.
=> Working tests from #53

README.md, library/network_connections.py, tests/test_network_connections.py
* by default ```name``` is used as ```interface_name```
* if ```interface_name``` is set to the empty string, it will not be set
* if ```mac``` is specified, ```interface_name``` defaults to not being set
This fixes #41
=> Use profile name for interface name by default

tasks/main.yml
The list of packages to install depends on the network provider, so
print it out early.
=> Print network provider early

tasks/main.yml
The service facts create too much noise in test logs, therefore hide
them.
=> tasks: Do not log full service facts

.travis.yml, molecule/default/Dockerfile.j2, molecule/default/molecule.yml, molecule/default/yamllint.yml, tox.ini
Configures Molecule to do basic checks (lint/syntax, run, idempotence, Ansible check mode functionality) of the role with default parameters (tests/tests_default.yml) using Travis CI and centos6/7 docker containers.
Because Travis was already used by network role, please check mainly .travis.yml, whether it makes sense to incorporate molecule into it in this way.
=> Configure Molecule in Travis CI

tests/ensure_non_running_provider.py, tests/playbooks/tests_vlan_mtu.yml, tests/tests_vlan_mtu_initscripts.yml, tests/tests_vlan_mtu_nm.yml
Test setting the MTU interfaces. This needs autoconnect:false for now,
possibly because of a bug in NetworkManager.
This tests that #101 works but because of #102 it cannot enable autoconnect (which is the default, therefore it is explicitly disabled here).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/110)
=> tests: Test setting the MTU of VLAN interfaces

tox.ini
Fedora 30 uses tox 3 which does not work with Python 2.6 out of the box.
Setting the install and list_dependencies commands to run `pip` instead
of `python -m pip` seems to fix this for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/117)
=> tox: Work around Python 2.6 issues with tox 3

library/network_connections.py, module_utils/network_lsr/utils.py
Create a checkpoint before changing NetworkManager profiles and rollback
on failures (destroy it on success).
This fixes #33 
Deferred integration tests, since the code is covered by the other tests. only the rollback is not tested. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/119)
=> Modules/NM: Wrap changes in checkpoint

defaults/main.yml
Oracle Linux is a RHEL clone and therefore needs to be included alongside RedHat and CentOS when deciding which packages need to be installed. OracleLinux versioning follows the same scheme as RedHat/CentOS.
=> Added OracleLinux as a RHEL clone for package detection purposes.

.travis.yml
Python 3.8 was released and will be used in Fedora Rawhide/Fedora 32.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/137)
=> Travis: Add stable Python 3.8, remove 3.7-dev

custom_requirements.txt
Specify on which environments PyYAML should be installed to prevent
failing pip install.
=> custom_requirements.txt: Add environment marker

.travis/config.sh, .travis/preinstall, .travis/utils.sh
This is a first batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- document used/introduced environment variables in comments
- use absolute pathes to `config.sh` and `utils.sh`
- include `config.sh` unconditionally (`config.sh` is now a part of template, so it is created by autosynchronization script if it does not exist)
- if `python` is a system python, install `python3-selinux` (`python3-selinux` is installed by default; in case there is a reason to not install `python3-selinux`, it can be removed from `LSR_EXTRA_PACKAGES` by `config.sh`)
- install `LSR_EXTRA_PACKAGES` in one command (increase performance)
=> Onboard refactored tox & Travis CI setup and configuration vol. 1

.travis/runpytest.sh, tox.ini
This is a second batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- shell wrapper around `pytest` (decides when to run `pytest` and with what arguments - some system roles do not contain Python code which confuses `pytest`)
=> Onboard refactored tox & Travis CI setup and configuration vol. 2

.travis/config.sh, .travis/runblack.sh, tox.ini
This is a third batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- wrap `black` - some system roles want not to run `black` on their code, so allow to control `black` via `config.sh`
=> Onboard refactored tox & Travis CI setup and configuration vol. 3

.travis/config.sh, .travis/custom_pylint.py, .travis/runpylint.sh, tox.ini
This is a 4th batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- rename `run_pylint.py` to `custom_pylint.py` (this is what the script really is - a customized `pylint`) and move it to `.travis/` directory where all auxiliary scripts should be placed
- call `custom_pylint.py` via shell wrapper so environment variables set by `config.sh` takes effect also when `tox` runs locally
=> Onboard refactored tox & Travis CI setup and configuration vol. 4

.travis/config.sh, .travis/runflake8.sh, tox.ini
This is a 5th batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- wrap `flake8` into a shell script so users can dissable it via `config.sh`
=> Onboard refactored tox & Travis CI setup and configuration vol. 5

.travis/config.sh, molecule_extra_requirements.txt, molecule_requirements.txt, tox.ini
This is a 6th batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- remove `LSR_MOLECULE_DEPS` environment variable (instead, use `molecule_extra_requirements.txt` permanently as a place where to add additional molecule dependencies)
- permanently add `selinux` to molecule dependencies (molecule needs it on selinux enabled systems to setup containers)
=> Onboard refactored tox & Travis CI setup and configuration vol. 6

.travis/runsyspycmd.sh, .travis/utils.sh, tox.ini
This is a 7th batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- `runsyspycmd.sh` script - runs a given command only if venv Python matches the system Python (this prevents failing when some command depends on binary libraries)
- put `molecule --version` and `ansible --version` to a standalone testenv (`[testenv:molecule_version]`) so a user can display molecule and ansible version by typing `tox -e molecule_version` without running `molecule lint`
=> Onboard refactored tox & Travis CI setup and configuration vol. 7

.travis.yml, .travis/config.sh, .travis/custom.sh, .travis/runtox, tox.ini
This is an 8th batch of changes introduced by PR #133 (changes are introduced in batches to make reviews easier). List of changes introduced in this PR:
- allow to run Molecule tests against more versions of Ansible
- allow to run custom commands also for Python 3.8-dev
- remove unecessary comment
=> Onboard refactored tox & Travis CI setup and configuration vol. 8

tox.ini
Molecule version 3 and later needs a different configuration file for
linters. This breaks the CI. Pin molecule to version 2 for now to
fix the CI until we have a proper fix.
=> Tox: Pin molecule to version 2

.travis.yml
Python 3.8-dev seems to be broken on Travis, disable it for now.
=> Travis: Disable Python 3.8-dev

.travis/custom_pylint.py, molecule/default/molecule.yml
This PR propagates files from [linux-system-roles/template](https://github.com/linux-system-roles/template) which should be in sync across [linux-system-roles](https://github.com/linux-system-roles) repos. In case of changing affected files via pushing to this PR, please do not forget also to push the changes to [linux-system-roles/template](https://github.com/linux-system-roles/template) repo.
Revision: [`782da17bfe474df40851ccf96f87d9a1ecb9ce0e`](https://github.com/linux-system-roles/template/tree/782da17bfe474df40851ccf96f87d9a1ecb9ce0e)
CC: @i386x, @pcahyna
=> Synchronize files from linux-system-roles/template

.yamllint.yml, molecule/default/molecule.yml, tests/ensure_non_running_provider.py, tests/get-coverage.yml, tests/playbooks/tests_ethtool_features.yml, tests/playbooks/tests_vlan_mtu.yml, tests/tests_bridge.yml, tests/tests_bridge_other_provider.yml, tests/tests_default_initscripts.yml, tests/tests_default_nm.yml, tests/tests_ethernet_other_provider.yml, tests/tests_ethtool_features_nm.yml, tests/tests_helpers-and-asserts.yml, tests/tests_states.yml, tests/tests_unit.yml, tests/tests_vlan_mtu_nm.yml, tox.ini
~~Update to the new molecule linter config. Also move the yamllint config
to the repo root directory to make it possible to use yamllint directly.~~
Changed it to only contain the yamllint config change and an update to tox to let it run yamllint.
=> molecule/tox: Support yamllint without molecule

.travis.yml, .travis/custom.sh, .travis/runblack.sh, .travis/runflake8.sh, .travis/runpylint.sh, .travis/runpytest.sh, .travis/runsyspycmd.sh, .travis/utils.sh, tox.ini
Many of the tests and tasks invoked from `tox` would try to use
the path to the `python` executable in the tox virtualenv, and
in some cases, would try to follow the symlink if the `python`
command were a symlink, in some cases, following the symlink to
the system python, and trying to use the absolute path.  This
would fail in some cases because when using the system python
with the absolute path, the python modules installed in the
tox venv could not be found.  So instead, just use the `python`
command from the venv with no path.
also enable travis 3.8-dev testing, since this fix allows that
platform to work correctly.
=> use python instead of envpython

.travis/runblack.sh, .travis/runflake8.sh, .travis/runpytest.sh, .travis/runsyspycmd.sh, .travis/utils.sh
NOTE: I don't think this commit directly affects network, since
network doesn't use any of these - this PR is more for parity
with template and other repos.
Centralize the setting of `ME` and `TOPDIR` in utils.sh
Add support for `RUN_FLAKE8_EXTRA_ARGS` and `RUN_BLACK_EXTRA_ARGS`
=> allow more overrides of template code

.travis/config.sh, .travis/runpylint.sh, .travis/runpytest.sh, .travis/utils.sh, tests/setup_module_utils.sh, tox.ini
This does not directly affect network because network has its own
solution for dealing with testing/linting module_utils code, but
it gets network to feature/code parity with the template and
other repos.
Defines a shell function in utils.sh - lsr_setup_module_utils -
that allows configuring a tox venv installed ansible to have
the repo module_utils code in the default pythonpath for the
venv, which allows testing and linting the module_utils code
without having to otherwise munge or mock the pythonpath.
Projects needing this functionality can set in `.travis/config.sh`
the variable `RUN_PYTEST_SETUP_MODULE_UTILS` to setup
module_utils/ for pytest, and `RUN_PYLINT_SETUP_MODULE_UTILS`
to setup module_utils/ for pylint.
=> support testing/linting module_utils code

.travis/preinstall, ansible_pytest_extra_requirements.txt, pytest_extra_requirements.txt, tox.ini
This doesn't affect network because network does not use ansible
for pyunit testing, so this commit is primarily to be in sync with
the template and other repos.
However, if you need `ansible` and `mock` for unit testing or
linting, see `pytest_extra_requirements.txt`
=> python 2.6 support for pytest and ansible 2.6

tests/get-coverage.yml
Update tests/get-coverage.yml
Coverage: Use find and file module instead of shell command #177
=> Coverage: Use find and file module instead of shell command

library/network_connections.py, tests/ensure_non_running_provider.py, tests/playbooks/tests_checkpoint_cleanup.yml, tests/tests_regression_nm.yml
If there is a NetworkManager checkpoint, roll it back on any failure.
Otherwise future invocations of the role fail until the checkpoint timed
out.
closes #154
=> Library/NM: Always rollback checkpoint on failure

library/network_connections.py, tests/ensure_non_running_provider.py, tests/playbooks/tests_reapply.yml, tests/tests_reapply_nm.yml
This includes one shared commit with #119 
Fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/121)
=> Try to reapply changes

defaults/main.yml
Some tests were getting the following error:
```
Unexpected templating type error occurred on ({{
network_connections |
json_query('[*][ieee802_1x]') | flatten | count > 0 }}): 'NoneType'
object is not iterable"
```
In general it is better to avoid the use of `json_query` and use
the older built-in jinaj2 filters such as `selectattr`, unless you
need to perform a complex query of complex json data.  In this
case, not sure what the problem was with the input json, but
using `selectattr` seems to have fixed it.
=> use selectattr instead of json_query

tox.ini
Move several common options to testenv instead of base to simplify the
file and use normal tox inheritance.
There is probably more potential for simplification but these seem to be some easy cases.
=> tox: Move common options to testenv

library/network_connections.py, tasks/main.yml, tests/playbooks/tests_ethernet.yml, tests/playbooks/tests_reapply.yml, tests/tasks/assert_output_in_stderr_without_warnings.yml, tests/tests_default.yml
Logs are now separed by severity level. Warnings and Failures are treated like
before, but debug and info logs are saved into a new json parameter called
"info_debug" that is later shown by a new created task.
In order to achieve a better readability, debug and info logs are shown as
warnings in case of failure like before, and also in "info_debug". If there is
not any failure, debug and info logs are never shown as warnings.
=> library: Separate debug and info logs from warnings

README.md, examples/bond_simple.yml
There was no documentation of the supported bond options.
Added supported options to the README.md and added an example of a
simple bond with both of those options.
Resolves #220
=> Document setting bond options

library/network_connections.py, module_utils/network_lsr/utils.py
According to PEP8 [1], the import are always put at the top of the file,
just after any module comments and docstrings, and before module globals
and constants.
=> library: all the imports must be on the top

defaults/main.yml, library/network_connections.py, module_utils/network_lsr/ethtool.py, module_utils/network_lsr/utils.py, tests/unit/helpers/ethtool, tests/unit/test_network_connections.py
This patch implements the ETHTOOL_GPERMADDR command in order to retrieve
the permanent address from ethtool instead using command line tool.
=> ethtool: use GPERMADDR instead the ethtool command line tool

defaults/main.yml, tasks/main.yml
To avoid conflicts with other roles, it is recomended to prefix all variables
that are only used internally with '__' and the name of the role ('__network_').
See discussion here: https://github.com/linux-system-roles/network/pull/157#discussion_r420965924
=> Prefix all local role variables with '__network'

README.md, examples/ethtool_features.yml, library/network_connections.py, module_utils/network_lsr/argument_validator.py, module_utils/network_lsr/nm_provider.py, tests/playbooks/tests_ethtool_features.yml, tests/unit/test_network_connections.py, tests/unit/test_nm_provider.py
Ethtool features should use underscores instead of dashes. A
warning shows in case dashes used, and it fails if underscore and dashes are
mixed.
=> library: Change ethtool features to use underscores

tests/tasks/test_802.1x_capath.yml
this addresses #245 and adds a proper check for the reason the role failed.
=> Fix ca_path test

module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_802_1x.yml, tests/unit/test_network_connections.py
When persistent_state is present and state is set to present or absent, a
ValidationError raises. A unit test validating this has been added.
Ref #205 
=> Fail if state and persistent_state are incompatible

library/network_connections.py
Since `invocation` is an Ansible special value that is set for
triple verbosity, it is now visible for smaller verbosity. Therefore
rename it to `_invocation`, which seems to work with less verbosity.
Also adjust the content to match the regular `invocation` style.
=> library: Rename invocation return value

tests/ensure_provider_tests.py, tests/tests_802_1x_nm.yml, tests/tests_802_1x_updated_nm.yml, tests/tests_bridge_initscripts.yml, tests/tests_bridge_nm.yml, tests/tests_ethernet_initscripts.yml, tests/tests_ethernet_nm.yml, tests/tests_ethtool_features_nm.yml, tests/tests_reapply_nm.yml, tests/tests_states_nm.yml, tests/tests_vlan_mtu_initscripts.yml, tests/tests_vlan_mtu_nm.yml, tests/tests_wireless_nm.yml
To allow selecting tests with tags, tasks essential tasks need to be
tagged as always to ensure that they are not accidentally skipped when
specifying a tag for a test.
=> Provider sets: Always run essential tasks

module_utils/network_lsr/argument_validator.py, tests/unit/test_network_connections.py
Since the order of the actions list does not matter anymore because the
role iterates over all actions in a defined order, simplify the
handling for persistent states.
=> Simplify persistent state handling

.travis/runtox, tox.ini
Travis CI is using a version of Docker server that supports API version 1.38.  However, the Python PYPI package `docker` version 4.3 was recently released which uses Docker server API version 1.39, and there is apparently no way to tell molecule to configure the `docker` Python API to use a different API.  The solution is to install the latest 4.2.x version of the `docker` Python PYPI package.
=> Fix Travis CI issue with Docker server API version mismatch

molecule_extra_requirements.txt
This fixes the following traceback:
Traceback (most recent call last):
[...]
File "/home/travis/build/linux-system-roles/network/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 775, in expand_path_vars
path = path.strip()
AttributeError: 'PosixPath' object has no attribute 'strip'
Reference: https://travis-ci.com/github/linux-system-roles/network/jobs/373270149
=> molecule: Hardcode ansible-lint version

tasks/main.yml
Ansible with molecule warns because the default mode changed. The new
default mode seems to be wrong so specify the correct one.
=> Tasks: Explicitly specify file mode

tests/playbooks/tests_states.yml, tests/tasks/get_NetworkManager_NVR.yml
To allow running the tests on any arch, do not check for the RPM
architecture when checking the NetworkManager version.
=> tests: Do not check arch for NM version

pylint_extra_requirements.txt, tests/integration/conftest.py, tests/integration/test_ethernet.py, tests/playbooks/integration_pytest_python3.yml, tests/tests_integration_pytest.yml
tests/integration/test_ethernet.py is a script capable of using the network
module without executing it from Ansible and using Pytest. The example test
sets an ip in a test interface.
=> Add Pytest integration tests

meta/main.yml
Galaxy imports of the network role are failing:
https://galaxy.ansible.com/my-imports/1710
```
Task "703539" failed: Command '['git', 'clone', '--quiet', '--depth', '1', '--branch', 'master', 'https://github.com/linux-system-roles/network.git', '/var/tmp/galaxy/imports/tmpnxdxwzmg']' returned non-zero exit status 128.
```
We need to tell galaxy to use `main` instead of `master`.  The galaxy
roles documentation says that `github_branch` may be used for this
purpose:
https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata
=> use github_branch: main for galaxy import

.github/stale.yml
To ensure that old/untouched pull requests do not pile up, configure the
probot stale bot to mark pull requests without activity in the last 14
days as stale and close them after 14 more days if there is no further
activity. The pull requests are marked with the stale label.
=> github: add stale workflow

README.md, contributing.md
All links containing references to the "master" branch must be replaced
by the "main" branch.
=> README.md: replace reference to "master" branch with "main" branch

library/network_connections.py, module_utils/network_lsr/nm/__init__.py, module_utils/network_lsr/nm/active_connection.py, module_utils/network_lsr/nm/client.py, module_utils/network_lsr/nm/error.py, module_utils/network_lsr/nm/provider.py, tests/integration/test_ethernet.py
When deactivating a profile in libNM, we should:
* Check `NM.ActionConnection` existence
* Check `NM.ActionConnection.props.state` not DEACTIVATED
* Use signal `state-changed` of `NM.ActionConnection`.
* Only invoke `NM.Client.deactivate_connection_async()` if not
in DEACTIVATING state.
* Ignore `NM.ManagerError.CONNECTIONNOTACTIVE` error.
This patch also introduced a new class `NetworkManagerProvider`
in `module_utils/network_nm_lsr`:
* Independent from Ansible but need to use absolute import due to limitation of ansible 2.8.
* Provide sync function wrapping async calls of libNM.
* Use stable logging method of python.
* Only load this module when provider is nm.
This patch also changed how logging is handling in
`Cmd_nm.run_action_down()` as initial step on isolate ansible log
mechanism …
=> nm provider: Refactor the down action of network connection

tests/tasks/test_802.1x_capath.yml
The Fedora 33 cloud image does not have openssl installed by default,
install openssl before using its cli tool.
=> test 802.1x: Install openssl as test dependency

tests/tasks/manage_test_interface.yml
Bring the test veth peer up and set as managed by NetworkManager when
possible.
=> test env: Bring test veth peer up

tests/integration/test_ethernet.py, tests/tasks/assert_profile_absent.yml, tests/tasks/assert_profile_present.yml, tests/tasks/get_profile_stat.yml
The NetworkManager in Fedora 33 does not use ifcfg-rh plugin by default,
the CI will fail on Fedora 33 with:
```
TASK [assert that profile 'bond0' is present] **********************************
task path: /tmp/tmpaz9m374e/tests/playbooks/tasks/assert_profile_present.yml:4
fatal: [/cache/fedora-33.qcow2]: FAILED! => {
"assertion": "profile_stat.stat.exists",
"changed": false,
"evaluated_to": false,
"msg": "profile /etc/sysconfig/network-scripts/ifcfg-bond0 does not exist"
}
```
Previously, we are checking the existence of
`/etc/sysconfig/network-scripts/` to determine whether ifcfg-rh plugin
is enabled. This is incorrect on Fedora 33.
The fix is checking the FILENAME[1] used for storing the NetworkManager
connection, the profile is considered as exists when it exists and does
not contains …
=> test: Fix profile assertion on Fedora 33

library/network_connections.py
The line was too long, and needed to be wrapped in a way that was
compatible with python black formatting.
=> Fix python line length problem

.github/workflows/tox.yml, molecule/default/Dockerfile.j2, molecule/default/molecule.yml, molecule_extra_requirements.txt
Use the new vault.centos.org repos.  Fix the yum repo configs in the
image if necessary to use these new repos.
Use the standard centos images from the centos registry rather than
custom lsr images from dockerhub.
Add support for centos8.  Note that using ansible 2.7 on centos8 requires
setting /usr/bin/python3 to be the ansible python interpreter.  Later
versions of ansible have better auto-detection.  We can get rid of this
once we drop support for ansible 2.7
Use tox-lsr 1.0.1
=> Fix centos6 repos; use standard centos images; add centos8

.github/workflows/tox.yml
Since we have disabled linting in molecule, use tox for running
ansible-lint.
=> add ansible-lint to github actions

pytest_extra_requirements.txt, tests/integration/test_ethernet.py, tests/playbooks/integration_pytest_python3.yml, tests/tasks/get_modules_and_utils_paths.yml, tests/tests_unit.yml, tests/unit/test_network_connections.py
The unit tests that are run during integration test did not
work for the role converted to collection format.  The tests need to
get the paths from the environment then set up the runtime environment
to look like the real Ansible runtime environment.
=> collections - working unit tests during integration

library/network_connections.py, module_utils/network_lsr/nm/connection.py, module_utils/network_lsr/nm/provider.py
Refactor the volatilize action of nm provider:
* Move code to `module_utils/network_lsr/nm`
* The `module_utils/network_lsr/nm` only delete profile by given UUID
instead of guess. The `library/network_connections.py` is responsible
on choosing UUID.
=> nm provider: Refactor the volatilize action of network connection

tests/tasks/get_modules_and_utils_paths.yml
This fixes the following error:
```
/bin/sh: line 9: cd: /root/.ansible/collections: No such file or directory
```
The fix is to ensure the directory exists before attempting
to `cd` to the directory.
=> fix collection lookup problem

.github/workflows/tox.yml
Use the new https://github.com/linux-system-roles/lsr-gh-action-py26 for running unit tests on python 2.6.  This uses an EL6 VM so more closely corresponds to the managed hosts that still use python 2.6.
=> use lsr-gh-action-py26 for python 2.6 unit tests

.ansible-lint, tests/get_coverage.yml, tests/playbooks/integration_pytest_python3.yml, tests/playbooks/tests_checkpoint_cleanup.yml, tests/playbooks/tests_eth_dns_support.yml, tests/playbooks/tests_ethtool_coalesce.yml, tests/playbooks/tests_ethtool_features.yml, tests/playbooks/tests_ipv6_disabled.yml, tests/playbooks/tests_reapply.yml, tests/tasks/cleanup_802_1x_server.yml, tests/tasks/cleanup_mock_wifi.yml, tests/tasks/create_test_interfaces_with_dhcp.yml, tests/tasks/el_repo_setup.yml, tests/tasks/enable_epel.yml, tests/tasks/get_current_interfaces.yml, tests/tasks/get_modules_and_utils_paths.yml, tests/tasks/get_profile_stat.yml, tests/tasks/manage_test_interface.yml, tests/tasks/remove_test_interfaces_with_dhcp.yml, tests/tasks/run_test.yml, tests/tasks/setup_802_1x_server.yml, tests/tasks/setup_mock_wifi.yml, tests/tasks/test_802.1x_capath.yml, tests/tests_unit.yml
That is the following errors are fixed.
'206'  # Variables should have spaces before and after: {{ var_name }}
'208'  # File permissions unset or incorrect
'301'  # Commands should not change things if nothing needs doing
'305'  # Use shell only when shell functionality is required
'502'  # All tasks should be named
'601'  # Don't compare to literal True/False
'602'  # Don't compare to empty string
RHELPLAN-73471
Signed-off-by: Noriko Hosoi <nhosoi@redhat.com>
=> Cleaning up ansible-lint errors except '106', '303' and '403'

library/network_connections.py, module_utils/network_lsr/utils.py, tests/unit/test_network_connections.py, tests/unit/test_nm_provider.py
There was recently an upgrade to python black which made function
documentation checking stricter.  This caused network tox CI to
break.  The fix is to format the function doc text in the manner
expected by black.
=> fix python black issues

tests/ensure_provider_tests.py, tests/tests_ethtool_coalesce_nm.yml, tests/tests_ethtool_features_nm.yml, tests/tests_provider_nm.yml
To clearly explain to user why minimum version or extra running
condition is needed for certain "NM_ONLY_TESTS", include additional
comment support.
=> Enable comment support for "NM_ONLY_TESTS"

tests/playbooks/tests_bond_deprecated.yml
Running `tests_bond_deprecated_initscripts.yml` and
`tests_bond_initscripts.yml` consecutively will fail in the downstream
testing with error "Determining IP information for nm-bond...dhclient is already running - exiting.".
Because the two tests have the same controller device name and dhclient
will always running for the controller device `nm-bond`.
A workaround for this bug is to change the controller device name
associated with `tests_bond_deprecated_initscripts.yml`.
Signed-off-by: Wen Liang <wenliang@redhat.com>
=> fix: dhclient is already running for `nm-bond`

tests/tasks/enable_epel.yml
In tests/tasks/enable_epel.yml, if /etc/yum.repos.d/epel.repo exists
and it is not enabled, it's left disabled. Without the epel enabled,
it fails to install necessary modules such as python-mock, which
makes tests_unit.yml and tests_wireless_nm.yml fail.
This patch adds a task calling ini_file to ensure the repo is always
enabled. See also bz1980439.
=> EPEL yum repository configuration for tests

tests/playbooks/integration_pytest_python3.yml
Previously when we run `tests_integration_pytest.yml` in RHEL 8, device
becoming unmanaged and NM `ifup` command failed to bring up the
connection when running pytest with initscripts, because network scripts
are deprecated in RHEL8 and they are no longer provided by default.
To fix that, install `network-scripts` package to utilize the legacy
`ifup` command.
=> fix: pytest not reproducible in RHEL8

tests/ensure_provider_tests.py, tests/tests_802_1x_nm.yml, tests/tests_802_1x_updated_nm.yml
The tests expect there is a hostapd package for doing wireless testing,
and that this package comes from EPEL on EL platforms.  Since there
is no EPEL9, skip tests that require hostapd.
=> Skip tests on RHEL9 that use hostapd

.github/Dockerfile.c8-network-role, .github/Dockerfile.c8s-network-role, .github/run_test.sh, .github/workflows/integration.yml, tests/tasks/create_test_interfaces_with_dhcp.yml, tests/tasks/remove_test_interfaces_with_dhcp.yml
Using container to run `ansible-playbook` against localhost.
To debug it, try
```bash
sudo DEBUG=1 ./.github/run_test.sh tests_bond_nm.yml
```
Attached two container files for CentOS 8 and CentOS Stream 8.
The container image is stored under quay:
https://quay.io/repository/linux_system_roles
Only a small mount of tests has been chose in order to give stable CI
test feedback.
The github action CI will run two instances using above container image.
=> CI: Enable integration test in Github Action

.github/workflows/integration.yml, tests/tests_802_1x_nm.yml, tests/tests_802_1x_updated_nm.yml
The commit b4584c88a8064aff9de84a15439b91772cb00bec to skip
tests that use hostapd also removed the epel repo setup.  This
breaks other platforms that require epel.
=> should not have removed epel setup from 802 tests

tests/playbooks/tests_bond.yml
The `tests_bond_initscripts.yml` will leave the VM holding the testing
DNS entry (nameserver 192.0.2.1) which break network connection.
The root cause is initscript will use dhcp-client for bond DHCP testing
which override the /etc/resolv.conf file. After test bond interface been
removed, the initscript will not restore the DNS settings.
The fix is backup the /etc/resolv.conf and restore it on clean up for
initscript provider.
=> test: Restore the resolv.conf for bond dhcp test

.github/run_test.sh
Prefer pre-existing https://quay.io/organization/linux-system-roles over
newly created https://quay.io/organization/linux_system_roles one.
=> CI: Fix the correct container image name.

tests/tasks/enable_epel.yml
For ansible-core 2.11 compatability, replace the use of `ini_file`
with the yum/dnf config-manager command
=> replace ini_file with yum/dnf

tests/unit/test_network_connections.py
When IPv6 is disabled, it is conflicting with enabling `auto6`
or configuring static IPv6 or configuring `gateway6` or
configuring `route_metric6`. Add unit tests to check if
this is properly handled in Argvalidator.
=> validate that ipv6_disabled is conflicting with other settings

module_utils/network_lsr/argument_validator.py, tests/unit/test_network_connections.py
When IPv6 is not configured, configuring IPv6 DNS should not be
allowed. Reject such a setting in argvalidator and add unit test to
verify that.
=> reject `dns` setting if IPv6 is not configured

module_utils/network_lsr/argument_validator.py, tests/unit/test_network_connections.py
NetworkManager only allows to configure the DNS options for each IP
family, when they are enabled. Therefore, reject DNS settings in
ArgValidator if no IP family is enabled.
=> Reject DNS_search setting if no IP family is enabled

.github/Dockerfile.c9s-network-role, .github/run_test.sh, .github/workflows/integration.yml
Skipped the 802.1x test due to missing hostapd rpm.
=> [citest skip] CI: Enable CentOS 9 stream integration test

.github/run_test.sh
To ensure that new tests are going to be tested by the CI, only exclude
tests that are not supported instead of only included the supported
ones.
=> [citest skip] GitHub CI: Exclude unsupported tests

tests/ensure_provider_tests.py, tests/tests_auto_gateway_initscripts.yml, tests/tests_bond_deprecated_initscripts.yml, tests/tests_bond_initscripts.yml, tests/tests_bridge_initscripts.yml, tests/tests_default_initscripts.yml, tests/tests_ethernet_initscripts.yml, tests/tests_ethtool_coalesce_initscripts.yml, tests/tests_ethtool_features_initscripts.yml, tests/tests_ethtool_ring_initscripts.yml, tests/tests_ipv6_initscripts.yml, tests/tests_states_initscripts.yml, tests/tests_switch_provider.yml, tests/tests_vlan_mtu_initscripts.yml
The initscripts provider tests are unstable on Fedora and users are not
using the initscripts on Fedora, therefore, disable all initscripts
provider tests on Fedora.
=> Disable all initscripts provider tests on Fedora

.github/workflows/tox.yml, pytest_extra_requirements.txt
This needs to be adjusted once tox-lsr and lsr-gh-action-py26 are released.
=> pytest: Fix py26 unit tests

.yamllint.yml, tests/tasks/setup_802_1x_server.yml
The hostapd package cannot be installed via RHEL Repo until RHEL-8.6,
as a result, any RHEL-8 of which the version released before REHL-8.6
has to install the hostapd via CentOS Stream in order to run managed
host testing.
=> Fix hostapd package installation error

tests/tasks/create_test_interfaces_with_dhcp.yml
The tests are giving failures that are unfortunately being ignored.
One of which is that pidof is not available by default on all platforms,
and on some platforms is not available at all (el7).  Same with sysctl.
There are a couple of fixes:
* run the large embedded test `shell` with `set -euo pipefail` to
trigger script errors to be handled.
* install the procps or procps-ng package which provides the tools
such as pgrep, pkill, sysctl, etc.
=> use pgrep instead of pidof; ensure packages exist

module_utils/network_lsr/argument_validator.py
The correct bond mode is `active-backup` instead of `active_backup`.
Thanks to vpal who found this issue via
https://github.com/linux-system-roles/network/issues/475
=> InfiniBand bond: Fix typo of bond mode active-backup

.github/workflows/integration.yml
The network role is using `main` for the default branch, so this needs
to be used in the workflow definition.
=> GitHub CI: Trigger on main branch

tests/integration/test_ethernet.py
Running the pytest with nm provider failed in the downstream testing
because the "NM_CONTROLLED=no" appeared in
`/etc/sysconfig/network-scripts/ifcfg-testeth` which caused the veth
`testeth` strictly unmanaged by NetworkManager. To fix it, remove such
a connection profile when it is existed before running the pytest.
=> Remove connection profile before running pytest

tests/unit/test_network_connections.py
=> fix: class Python26CompatTestCase broken by minor python versions

tests/playbooks/tests_ipv6_dns_search.yml
ip.ipv6_disabled is not supported by the running version of
NetworkManager when testing on RHEL-7 or CentOS-7, therefore, skip the
tests on RHEL-7 or CentOS-7.
=> ipv6_disabled: Skip the tests on RHEL-7 or CentOS-7

defaults/main.yml, tasks/main.yml, tasks/set_facts.yml, tests/setup-snapshot.yml, tests/tests_default.yml
- support playbooks which use gather_facts: false
- add setup-snapshot.yml used to prepare testing snapshots
=> no gather facts setup snapshot

tests/tasks/assert_device_absent.yml, tests/tasks/assert_device_present.yml, tests/tasks/assert_profile_absent.yml, tests/tasks/assert_profile_present.yml, tests/tasks/manage_test_interface.yml, tests/tasks/show_interfaces.yml
The keyword `include:` is deprecated in favor of
`include_tasks:`.
See https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_module.html
=> change include to include_tasks

module_utils/network_lsr/argument_validator.py, tests/unit/test_network_connections.py
Accept any whitespace sequence, according to Python's `rb"\s"` class.
This way, tabs are also accepted.
Also add a unit test for the default iproute2 file.
Use just one regex for this.
---
https://github.com/linux-system-roles/network/issues/507
=> argument_validator: fix IPRouteUtils.get_route_tables_mapping() to accept any whitespace sequence

library/network_state.py
`libnmstate.show()` would include the info like bridge timer etc which
should not be considered when comparing between the previous state and
current state. Instead, using the the `libnmstate.show_running_config()`
which would filter out these kind of data.
=> network_state: improve state comparison for achieving idempotency

README.md, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_routing_rules.yml, tests/unit/test_network_connections.py
=> Support looking up named route table in routing rule

examples/bond_options.yml, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_bond_options.yml
Kernel allows to set `arp_all_targets` when `arp_interval` is disabled (disable ARP monitoring). But `arp_all_targets` specifies the quantity of `arp_ip_targets` that must be reachable in order for the ARP monitor to consider a slave as being up. It makes more sense to set the `arp_all_targets` while enabling the `arp_interval`.
=> bond: Test arp_all_targets only when arp_interval is enabled

tests/playbooks/tests_auto_gateway.yml, tests/playbooks/tests_bond.yml, tests/playbooks/tests_bond_deprecated.yml, tests/playbooks/tests_bond_options.yml, tests/playbooks/tests_bond_removal.yml
When creating a bond, the bond also creates a default route with a
default metric of 0.  This causes test failures on CI systems as
it overrides the system default route.  Use the new `ip.route_metric4`
parameter to set a high metric value so as not to override the
default system route.
Some systems cannot use a metric value of 32 bit unsigned int max value.  To ensure
the broadest possible support, use a metric value of 16 bit signed int max value,
which should be high enough to ensure the routes always have the lowest priority.
=> add ip.route_metric4: 65535 to failing bond tests

tests/tasks/enable_epel.yml
On BaseOS CI systems, `yum install` for the epel7 rpm does not work.
Instead, use `rpm -i` which should work on any system.  We should not
need to use `yum install` here because the epel7 setup rpm does not have
additional dependencies.
=> use rpm -i instead of yum install for epel7

CHANGELOG.md
[1.10.0] - 2022-11-01
- Support looking up named route table in routing rule
- Support 'route_metric4' for initscripts provider
- Support the DNS priority
- bond: improve the validation for setting peer_notif_delay
- bond: test arp_all_targets only when arp_interval is enabled
- bond: attach ports when creating the bonding connection
- Set the route metric when testing the 'auto_gateway'
- Fix markdownlint 'unordered list indentation' issue
- add ip.route_metric4: 65535 to failing bond tests
- use rpm -i instead of yum install for epel7
=> Version 1.10.0 - CHANGELOG.md [citest skip]

.ansible-lint, .yamllint.yml, examples/bond_options.yml, examples/bond_simple.yml, examples/bond_with_vlan.yml, examples/bridge_with_vlan.yml, examples/cloned_mac.yml, examples/dummy_simple.yml, examples/eth_dns_support.yml, examples/eth_simple_auto.yml, examples/eth_with_802_1x.yml, examples/eth_with_vlan.yml, examples/ethtool_coalesce.yml, examples/ethtool_features.yml, examples/ethtool_features_default.yml, examples/ethtool_ring.yml, examples/infiniband.yml, examples/ipv6_disabled.yml, examples/macvlan.yml, examples/match_path_support.yml, examples/network_state.yml, examples/remove+down_profile.yml, examples/route_table_support.yml, examples/team_simple.yml, examples/wireless_wpa3_owe.yml, examples/wireless_wpa3_sae.yml, examples/wireless_wpa_psk.yml, tasks/main.yml
The only thing we need to skip currently is using FQCN for ansible
builtin modules, plugins
Add `kinds` - otherwise, Ansible thinks anything not in a traditional
role path is a plain YAML file, and we don't get the additional
checking.
Ensure all plays are named.
Fix some other minor problems.
=> ansible-lint 6.x updates

tests/tasks/el_repo_setup.yml
Almost all the network role tests fail with fact gathering disabled. Therefore, in order to support the tests running with ANSIBLE_GATHERING=explicit, gather the minimum subset of facts required.
=> Support running the tests with ANSIBLE_GATHERING=explicit

.github/actions/custom-woke-action/LICENSE, .github/actions/custom-woke-action/README.md, .github/actions/custom-woke-action/action.yml, .github/actions/custom-woke-action/entrypoint.sh, .github/actions/custom-woke-action/testdata/bad.txt, .github/workflows/woke.yml, CHANGELOG.md, README.md, contributing.md, library/network_connections.py, module_utils/network_lsr/argument_validator.py, module_utils/network_lsr/ethtool.py, tests/ensure_provider_tests.py, tests/playbooks/tests_bond_options.yml, tests/unit/test_network_connections.py
Add check for non-inclusive language
Add a check for usage of terms and language that is considered non-inclusive. We are using the woke tool for this with a wordlist that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Note: this commit uses the customized woke placed locally in .github/actions/custom-woke-action to support a new option `--count-only-error-for-failure` option. The local action custom-woke-action will be replaced with the official woke once https://github.com/get-woke/woke/pull/252 (Add an option "--count-only-error-for-failure") is processed.
Clean up / Workaround non-inclusive words.
- CHANGELOG.md
- README.md
- contributing.md
- library/network_connections.py
- module_utils/network_lsr/argument_validator.py
- …
=> Add check for non-inclusive language; Clean up / Workaround non-inclusive words

tests/playbooks/tests_bond.yml, tests/playbooks/tests_bond_cloned_mac.yml, tests/playbooks/tests_bond_deprecated.yml, tests/playbooks/tests_bond_options.yml, tests/playbooks/tests_bond_removal.yml
The bond tests fail regularly in our single host downstream testing,
so mark them as `expfail` (expect to fail) so that these failures
do not clutter up our test results.
We have tried to fix this in the past - several times over the past
three years, at a cost of many man weeks of effort  - and the fixes just
don't seem to "take".  We have reached the point where we need to cut
our losses and just skip these tests.  Perhaps at some point in the
future we can revisit this issue.
=> tag all bond tests with expfail

CHANGELOG.md
[1.11.1] - 2023-01-24
- none
- none
- ansible-lint 6.x updates
- Support running the tests with ANSIBLE_GATHERING=explicit
- Clean up / Workaround non-inclusive words
- Add check for non-inclusive language
- fix the ansible-pull link, the old do not work
- tag all bond tests with expfail
=> Version 1.11.1 - CHANGELOG.md [citest skip]

.github/run_test.sh
Use `grep -E` instead of deprecated `egrep`
Ignore the "use double quotes" rule because we want the
variables to be expanded with all of the spaces.
=> address shellcheck issues

README.md
To allow a "non-inclusive word" in README.md, a wokeignore rule was added as follows.
```
"non-inclusive word" in kernel and NetworkManager.
```
When the markdown format is converged to the html format, the comment line is treated as a blank line proceeded by `<p>`.
```
<p><br />
"non-inclusive word" in kernel and NetworkManager.
```
Starting with `<p>` and being followed by`<br />`, the wokeignore rule loses the ability to make the inclusive language utility `woke` skip checking the non-inclusive word in the next line.
Instead of putting the wokeignore rule comment above the non- inclusive word, it's placed in the same line.
Signed-off-by: Noriko Hosoi <nhosoi@redhat.com>
=> Non-inclusive words - Fix wokeignore comment in README.md

.github/workflows/python-unit-test.yml
The PR https://github.com/linux-system-roles/network/pull/556
erroneously removed the python-26 job for unit testing.  This
PR adds it back.
See also https://github.com/linux-system-roles/.github/pull/10
=> add back python-26 unit test

.github/workflows/python-unit-test.yml
Use tox-lsr version 2.13.2 in order to pick up the codecov
fix.
https://github.com/linux-system-roles/tox-lsr/pull/109
=> use tox-lsr version 2.13.2

.github/workflows/python-unit-test.yml
Add a github action task to upload the coverage files
to codecov after the unit tests are complete.
=> Upload coverage files to codecov

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .github/workflows/codeql.yml, .github/workflows/integration.yml, .github/workflows/python-unit-test.yml, .github/workflows/shellcheck.yml
When adding an approved PR to the merge queue, the required status checks of the workflows are missing, which prevents the PR getting merged. This commit is intended to triggering merge group checks with Github Actions, so that the workflows will report the needed status checks.
=> [Draft] Add needed status check on the merge_group

.ansible-lint, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml
Update tox-lsr to 2.13.2
Update ansible-lint configuration
Add support for merge queues to github actions
This doesn't mean all system roles support merge queues,
this is just a preliminary step
See https://github.com/linux-system-roles/.github/pull/21
=> update tox-lsr to 2.13.2; update ansible-lint configuration; start of support for merge queues

tests/playbooks/integration_pytest_python3.yml, tests/playbooks/tests_bridge.yml, tests/playbooks/tests_bridge_cloned_mac.yml, tests/playbooks/tests_checkpoint_cleanup.yml, tests/playbooks/tests_eth_dns_support.yml, tests/playbooks/tests_ethernet.yml, tests/playbooks/tests_ipv6_disabled.yml, tests/playbooks/tests_network_state.yml, tests/playbooks/tests_route_table.yml, tests/playbooks/tests_routing_rules.yml, tests/playbooks/tests_states.yml, tests/playbooks/tests_switch_provider.yml, tests/playbooks/tests_team_plugin_installation.yml, tests/playbooks/tests_wireless_plugin_installation.yml, tests/tasks/assert_device_absent.yml, tests/tasks/assert_device_present.yml, tests/tasks/assert_profile_absent.yml, tests/tasks/assert_profile_present.yml, tests/tasks/delete_interface.yml, tests/tasks/get_modules_and_utils_paths.yml, tests/tasks/get_profile_stat.yml, tests/tasks/run_test.yml, tests/tasks/setup_mock_wifi_wpa3_owe.yml, tests/tasks/setup_mock_wifi_wpa3_sae.yml, tests/tasks/test_802.1x_capath.yml, tests/tests_helpers_and_asserts.yml, tests/tests_unit.yml
All names of the tasks should start with an uppercase letter.
=> ansible-lint: Fix name[casing] and jinja[spacing] warnings [citest skip]

tests/get_coverage.yml, tests/playbooks/manual_test_ethtool_coalesce.yml, tests/playbooks/tests_802_1x.yml, tests/playbooks/tests_bond.yml, tests/playbooks/tests_bond_cloned_mac.yml, tests/playbooks/tests_bond_deprecated.yml, tests/playbooks/tests_bond_options.yml, tests/playbooks/tests_bond_removal.yml, tests/playbooks/tests_checkpoint_cleanup.yml, tests/playbooks/tests_eth_pci_address_match.yml, tests/playbooks/tests_ethtool_coalesce.yml, tests/playbooks/tests_ethtool_features.yml, tests/playbooks/tests_ethtool_ring.yml, tests/playbooks/tests_infiniband.yml, tests/playbooks/tests_ipv6_dns_search.yml, tests/playbooks/tests_reapply.yml, tests/playbooks/tests_wireless.yml, tests/tests_change_indication_on_repeat_run.yml, tests/tests_unit.yml
In some test playbooks, the `ignore_errors: true` can not be replaced by `changed_when: false`, because `changed_when` is not a valid attribute for a IncludeRole.
=> ansible-lint: Fix ignore-errors failures

tests/playbooks/tests_states.yml, tests/tasks/run_test.yml
ansible-lint is confused by the use of `when:` with `lsr_assert_when`.
It thinks the `when` string should be evaluated as a Jinja expression
but it is really just a plain string.  To make this more friendly to
ansible-lint, use `condition:` instead of `when:` with
`lsr_assert_when`.
=> in lsr_assert_when use condition instead of when

templates/get_ansible_managed.j2, tests/tasks/assert_profile_present.yml, tests/tasks/get_profile_stat.yml
Add role name to the generated config files.
```
```
@tyll, @liangwen12year, @cathay4t,
This change is for an RFE described in RHELPLAN-77233. We'd like to have inputs from the network role team before applying this to the other roles. Could you please take a look at the ticket and this pr and share your feedback?
Thanks.
=> Fingerprint RHEL System Role managed config files

tests/get_coverage.yml
More name[casing] warnings are discovered by ansible-lint, this may be due to the upgrade of ansible-lint.
=> ansible-lint: Fix remaining name[casing] warnings

tests/tests_switch_provider.yml
The test `tests_switch_provider.yml` does not support running with `ANSIBLE_GATHERING=explicit`. Therefore, include the task 'el_repo_setup.yml' before running the test which supports gathering the minimum subset of facts required.
=> Fix the failure of running ANSIBLE_GATHERING=explicit on tests_switch_provider.yml

.ansible-lint, .commitlintrc.js, .github/workflows/commitlint.yml
For more information, see Conventional Commits format in Contribute https://linux-system-roles.github.io/contribute.html#conventional-commits-format
=> ci: Add commitlint GitHub action to ensure conventional commits with feedback

.yamllint.yml, tests/playbooks/tests_bond_cloned_mac.yml, tests/playbooks/tests_bond_options.yml
Use standard Ansible spacing for braces and brackets.  This
allows us to remove those rule exceptions from .yamllint.yml
=> style: Use standard Ansible braces and brackets spacing

.yamllint.yml, tests/setup-snapshot.yml, tests/tasks/el_repo_setup.yml, tests/tasks/setup_802.1x.yml
ansible-lint requires that YAML documents begin with a line
consisting of `---`
=> style: ansible-lint - fix missing YAML document start

.github/workflows/python-unit-test.yml
tox-lsr 3.x does not support python 2.6, so use tox-lsr 2.13 for
py26 testing.  This should be fine until we can drop support for
python 2.6
=> ci: Use tox-lsr 2.13 for py26

README.md, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_eth_dns_support.yml, tests/unit/test_network_connections.py
reason: The administrator wants to suppress the AAAA queries made by the stub resolver, including AAAA lookups triggered by NSS-based interfaces such as getaddrinfo. Only the DNS lookups are affected.
result: The administrator is able to suppress AAAA queries made by the stub resolver.
=> feat: Support "no-aaaa" DNS option

defaults/main.yml, tasks/set_facts.yml
Cause: The comparison of the present facts with the required facts is
being done on unsorted lists.
Consequence: The comparison may fail if the only difference is the
order.  Facts are gathered unnecessarily.
Fix: Use `difference` which works no matter what the order is.  Ensure
that the fact gathering subsets used are the absolute minimum required.
Result: The role gathers only the facts it requires, and does
not unnecessarily gather facts.
=> fix: facts being gathered unnecessarily

tests/playbooks/tests_infiniband.yml
Enhancement: Use variable to hold infiniband interface name
Reason: To avoid hard coded interface name used all over the place in `tests_infiniband.yml`, specify a variable to hold the variable name instead.
=> test: Use variable to hold infiniband interface name [citest skip]

defaults/main.yml, tests/playbooks/tests_bond.yml, tests/playbooks/tests_bond_cloned_mac.yml, tests/playbooks/tests_bond_deprecated.yml, tests/playbooks/tests_bond_options.yml, tests/playbooks/tests_bond_removal.yml, tests/tasks/enable_epel.yml
Enhancement:
fix: Add dhcp client package dependency for initscripts provider
Reason:
Initscripts provider requires `/sbin/dhclient` to obtain DHCP address, which is shipped in dhcp client package. But the managed hosts may not already install the dhcp client package, thus, add it as the dependency package for initscripts provider.
Result:
=> fix: Add dhcp client package dependency for initscripts provider

.github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .github/workflows/python-unit-test.yml
This is primarily for the update to ansible-plugin-scan to
work with the upcoming ostree changes, but also includes
some minor fixes which affect ci.
3.1.0 was released but not used due to a bug fixed in 3.1.1
See full release notes for 3.1.0 and 3.1.1
https://github.com/linux-system-roles/tox-lsr/releases
=> ci: tox-lsr version 3.1.1

CHANGELOG.md
Enhancement:
docs(changelog): Fix wrong format in version 1.13.2
Reason:
The changelog update for version 1.13.2 contains wrongly formatted content which makes the changelog file update inconsistent from previous release.
Result:
=> docs(changelog): Fix wrong format in version 1.13.2 [citest skip]

library/network_connections.py, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_routing_rules.yml, tests/unit/test_network_connections.py
Enhancement:
fix: Allow address 0.0.0.0/0 or ::/0 for 'from'/'to' in a routing rule
Reason:
`from 0.0.0.0/0` means from all IPv4 addresses, `from ::/0` means from all IPv6 addresses. In NM, if `from` property is not specified in a routing rule, NM still appends `from 0.0.0.0/0` or `from ::/0` to the rule. NM also allows to specify `to 0.0.0.0/0` or `to ::/0` in a routing rule, but the connection profiles will only show the `from` setting for the rule.
Result:
=> fix: Allow address 0.0.0.0/0 or ::/0 for 'from'/'to' in a routing rule

library/network_connections.py, module_utils/network_lsr/argument_validator.py, module_utils/network_lsr/utils.py, tests/unit/test_network_connections.py
Enhancement:
refractor: Use meaningful variable
Reason:
Some variables used in the module code are not meaningful at all, which mgiht be hard to read and understand. Therefore, replace them with meaningful variables.
Result:
=> refactor: Use meaningful variable

.github/run_test.sh, .ostree/get_ostree_data.sh, .sanity-ansible-ignore-2.11.txt, .sanity-ansible-ignore-2.12.txt, .sanity-ansible-ignore-2.13.txt, .sanity-ansible-ignore-2.14.txt, .sanity-ansible-ignore-2.15.txt, .sanity-ansible-ignore-2.9.txt, tests/covstats, tests/get_coverage.sh, tests/get_total_coverage.sh, tests/git-post-commit.sh, tests/git-pre-commit.sh, tests/merge_coverage.sh
Use the `#!/usr/bin/env bash` shebang which is ansible-test friendly.
This means we can remove get_ostree_data.sh from the .sanity* files.
This also means we can remove the .sanity* files if we do not need
them otherwise.  Fix other shell scripts to use the friendly shebang
and remove from the .sanity* files.
Rename `pth` to `path` in honor of nscott
=> refactor: get_ostree_data.sh use env shebang - remove from .sanity*

tests/tests_provider_nm.yml, tests/tests_regression_nm.yml
=> test: Skip running tests where initscripts is not supported

tests/tasks/setup_mock_wifi_wpa3_owe.yml, tests/tasks/setup_mock_wifi_wpa3_sae.yml
`uname -m` will show the machine hardware name.
Enhancement:
Reason:
Result:
=> tests: Fix installing kernel module in Fedora

tests/tasks/setup_mock_wifi_wpa3_owe.yml, tests/tasks/setup_mock_wifi_wpa3_sae.yml
CentOS Stream build process has been moved to
https://kojihub.stream.centos.org.
Enhancement:
Reason:
Result:
=> test: Fix wifi test failures

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .github/workflows/python-unit-test.yml
The old ansible-community ansible-lint github action is deprecated.
There is a new ansible-lint github action called `ansible/ansible-lint`.
However, this version requires a collection, so we have to convert
the role to collection format before running the ansible-lint action.
tox-lsr has been updated to use ansible-core 2.16 for ansible-lint and
ansible-test.
This also requires tox-lsr 3.2.1 - bump other actions to use 3.2.1
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
=> ci: Use new ansible-lint action, which requires collection format and 2.16

tests/playbooks/tests_wireless_wpa3_owe.yml, tests/playbooks/tests_wireless_wpa3_sae.yml
=> test: Clean up mock wifi at the end of each wireless test

tests/playbooks/tests_bond.yml, tests/playbooks/tests_bond_cloned_mac.yml, tests/playbooks/tests_bond_deprecated.yml, tests/playbooks/tests_bond_removal.yml, tests/tasks/cleanup_802_1x_server.yml, tests/tasks/create_test_interfaces_with_dhcp.yml, tests/tasks/remove_test_interfaces_with_dhcp.yml
Improve bond test failure debugging
* put test setup into block/always so that cleanup happens for setup failures
* trace shell commands so that we can determine exactly which command failed
* add error reporting so that when certain commands fail, we can determine the error code
=> test: improve bond test failure debugging

tests/ensure_provider_tests.py
Enhancement: Enabling testing team interface on Fedora.
Reason: Team interface is indeed supported on Fedora
Result: We can test the team interface on Fedora. 
=> tests: Team interface is indeed supported on Fedora

tests/playbooks/tests_team_plugin_installation.yml, tests/playbooks/tests_wireless_and_network_restart.yml, tests/playbooks/tests_wireless_plugin_installation.yml, tests/tasks/ostree_systems_check.yml, tests/tasks/setup_mock_wifi_wpa3_owe.yml, tests/tasks/setup_mock_wifi_wpa3_sae.yml, tests/tests_team_nm.yml, tests/tests_wireless_and_network_restart_nm.yml
Improve the name text for skipped ostree tests to explain
why the test is skipped.
=> test: improve name text for skipped ostree tests

examples/macvtap.yml
Enhancement: Improved Configuration for MAC VTAP
Reason: The current setup process for MAC VTAP lacks a standardized and reusable approach,Currently we are supporting MAC VTAP as "tap": True in macvlan. To address this, this pull request introduces a yml  file, "macvtap.yml", to provide a  structured method for configuring MAC VTAP. This enhancement aims to simplify the setup process and improve the usability of MAC VTAP.
Result: With the addition of the YAML "macvtap.yml" file, users can easily define and modify MAC VTAP settings by modifying this file. This will streamline the configuration process and enable users to customize MAC VTAP according to their specific requirements. 
Issue Tracker Tickets (Jira or BZ if any):  issue #285
=> docs: Add MAC VTAP example

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .github/workflows/python-unit-test.yml, .yamllint.yml, examples/eth_with_802_1x.yml, examples/macvtap.yml, library/network_connections.py, module_utils/network_lsr/argument_validator.py, module_utils/network_lsr/ethtool.py, tests/unit/test_network_connections.py
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
=> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

README.md
Enhancement Reason: To provide users with clear guidance on how to specify VLAN ID and settings for the "vlan" type, improving usability and clarity in network configuration.
Result: Users can now easily understand and configure VLAN-related settings using the updated documentation, leading to more efficient network setups.
Issue Tracker Tickets (Jira or BZ if any): [#491]
=> docs: Add documentation for specifying VLAN ID

README.md
Enhancement:Creating Document for the network_connections module
Reason:To guide users and developers  to use the network_connections module only  for internal usage
Result:with the adding of this documentation user and developers will understand No Direct Invocation for   network_connections module,they  should refrain from directly invoking the network_connections module outside of its designated role.
Issue Tracker Tickets (Jira or BZ if any):#292
=> docs: network_connections module is only meant for internal usage

tests/playbooks/tests_bond_deprecated.yml
When the test fails, gather additional information to help
diagnose the failure.
=> test: debug deprecated bond test failures

.ostree/packages-runtime-CentOS-10.txt, .ostree/packages-runtime-RedHat-10.txt, .ostree/packages-testing-CentOS-10.txt, .ostree/packages-testing-RedHat-10.txt, meta/main.yml, tasks/main.yml, tests/ensure_provider_tests.py, tests/tests_team_nm.yml, tests/tests_team_plugin_installation_nm.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
=> fix: add support for EL10

defaults/main.yml, tasks/main.yml
As part of the public API, `network_state` must be defined in
defaults/main.yml, and it must be defined with the correct
type `dict`, so the correct default value must be `{}` the
empty dict.
All checking for `network_state` must check for a value of
`{}` to mean "network_state not set or empty".
Fix the test which looks for teaming configuration in EL10
to correctly look for the value in `network_state`.
=> fix: network_state must be defined in defaults/main.yml

tests/playbooks/tests_team_plugin_installation.yml
The team plugin test does not clean up properly causing the following team
test to fail.  The fix is to use the network standard run_test.yml interface
to ensure proper preconditions and cleanup for the team plugin test.
=> test: team plugin test does not clean up properly

tests/playbooks/tests_auto_gateway.yml, tests/playbooks/tests_ethtool_features.yml, tests/playbooks/tests_ipv6.yml, tests/playbooks/tests_reapply.yml, tests/tasks/assert_IPv4_present.yml, tests/tasks/assert_IPv6_present.yml, tests/tasks/assert_bond_options.yml, tests/tasks/assert_bond_port_profile_present.yml
Do not use templating in `when:`, `that:`, `until:`.  These
are evaluated as Jinja statements.  In cases where the string
used is long or awkward to generate in-line, use an
intermediate var for the value.
Use a unique loop var instead of `item` in cases where a loop
may be called in a nested context.
Fix some formatting.
=> test: fix some Ansible warnings not caught by lint

README.md, library/network_connections.py, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_route_table.yml, tests/unit/test_network_connections.py
Enhancement: Add the optional route source parameter for the nm provider
Reason: In a scenario where you have a machine with multiple public IP
addresses, typically due to a multi-WAN setup, the src parameter in the
context of routes allows you to specify which source IP address should
be used when sending packets via a specific route.  This is crucial when
you want to ensure that outbound traffic uses a specific IP address tied
to a particular network interface, especially when dealing with multiple
WAN connections.
Result: Adding support for the src parameter in routes results in a
more powerful and flexible network configuration capability, especially
important in environments with multiple network interfaces or multiple
IP addresses, it provides better control over traffic routing. …
=> feat: Add the support for the optional route source parameter in nm provider

tests/tests_integration_pytest.yml
Something has changed in python, similar to the change between
el8 and el9, that causes the test to fail on f39 and later, so
skip it.
=> test: skip integration pytest on fedora 39 and later

.github/Dockerfile.c7-network-role, .github/Dockerfile.c8s-network-role, .github/run_test.sh
Use the vault for centos 7 and centos stream 8
Exclude tests/tests_team_plugin_installation_nm.yml since
tests/tests_team_nm.yml is excluded.
Use grouping to group log lines for better readability.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#grouping-log-lines
=> ci: fix and improve integration container testing

tests/tasks/enable_epel.yml
Enhancement:
Fix tests on EL-7
Reason:
EL-7 test were failing due to missing EPEL-7 packages/repository
Result:
EL-7 test should pass
#718
=> tests: Use EPEL-7 from archive

tests/tasks/create_test_interfaces_with_dhcp.yml, tests/tasks/remove_test_interfaces_with_dhcp.yml
If firewall is active, the dhcp services do not work.  Change the test
to add and remove the dhcp services if firewall is active.
=> test: allow dhcp service if firewall is active

tests/tasks/create_test_interfaces_with_dhcp.yml, tests/tasks/remove_test_interfaces_with_dhcp.yml
Need to test if firewalld is running - the is-active test is
for that, not is-enabled
=> test: use is-active instead of is-enabled to check for firewalld

examples/network_state_example.yml
=> docs: Add examples using network_state variable

examples/network_state_example.yml
For an ethernet device which contains the kernel link, we should not and cannot delete such a device using `network_state` variable.
=> docs: Remove invalid network state example

README.md, examples/eth_simple_auto.yml, library/network_connections.py, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_dummy.yml, tests/tasks/assert_autoconnect_retries.yml, tests/tasks/create_dummy_profile.yml, tests/unit/test_network_connections.py
Enhancement: feat: Support `autoconnect_retries`
Reason:
There is no fine-grained control over the number of retries for automatically reconnecting a network connection in the role. This limitation can be problematic for certain use cases where extending the retry process is critical, particularly in environments with unstable networks. Introduce support for the `autoconnect_retries` property in nm provider of `network_connections` variable. This feature allows users to configure how many times NetworkManager will attempt to reconnect a connection after a autoconnect failure, providing more control over network stability and performance.
Result:
=> feat: Support autoconnect_retries

README.md
=> docs: Promote `network_state` variable as the future for network management

defaults/main.yml, tests/vars/rh_distros_vars.yml
We have a lot of requests to support Rocky and Alma in various system roles. The
first part of adding support is adding `vars/` files for these platforms. In
almost every case, for a given major version N, the vars file RedHat_N.yml can
be used for CentOS, Rocky, and Alma.  Rather than making a copy of the
RedHat_N.yml file, just use a symlink to reduce size and maintenance burden, and
standardize this across all system roles for consistency.
NOTE: There is no Alma or Rocky version 7 or less.
NOTE: OracleLinux is not a strict clone, so we are not going to do this for
OracleLinux at this time.  Support for OracleLinux will need to be done in
separate PRs. For more information, see
https://github.com/linux-system-roles/cockpit/issues/130
**Question**: Why not just use …
=> refactor: Use vars/RedHat_N.yml symlink for CentOS, Rocky, Alma wherever possible

library/network_connections.py
Enhancement:
Updated the link_info_find method to prioritize matching links by perm-address when it is valid and available. If the perm-address is unavailable (None or "00:00:00:00:00:00"), the method falls back to matching by address. Additionally, if ifname is provided, it takes precedence and returns the corresponding linkinfo immediately.
Reason:
The change resolves scenarios where multiple network interfaces might
share the same current MAC address (address), leading to potential
ambiguity in link matching. By prioritizing the permanent MAC address
(perm-address), the method provides a more precise and consistent match.
This is particularly crucial in environments with:
- MAC address spoofing or dynamic changes, where the current MAC
address may not reliably identify the interface.
- …
=> fix: Prioritize find link info by permanent MAC address, with fallback to current address

module_utils/network_lsr/nm_provider.py, tests/ensure_provider_tests.py, tests/unit/test_network_connections.py, tests/unit/test_nm_provider.py
=> refactor: fix python black formatting

.codespellrc, plans/README-plans.md, plans/test_playbooks_parallel.fmf
* Calculate number of managed nodes with this formula:
(( number_of_test_playbooks / 10 + 1 ))
* Add README explaining how to run the plan locally and remotely
=> ci: Add test plan that runs CI tests and customize it for each role

module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_routing_rules.yml
The validation was incorrectly checking for routing rule attributes at the top-level NM module instead of the NM.IPRoutingRule class. This was causing validation failures because:
libnm's API has two core aspects:
1. NMConnection/NMSetting types for handling connection profiles
2. NMClient as a cache of D-Bus objects
The suppress_prefixlength and uid_range attributes are not part of the top-level NM module but belong to NM.IPRoutingRule. Updated the validation to properly check for:
- set_suppress_prefixlength instead of NM_IP_ROUTING_RULE_ATTR_SUPPRESS_PREFIXLENGTH
- set_uid_range instead of NM_IP_ROUTING_RULE_ATTR_UID_RANGE_START
This aligns with the correct API usage and fixes the validation errors.
Enhancement:
Reason:
Result:
Resolves: …
=> fix: Correct attribute checks for routing rule validation

tests/provision.fmf
The latest version of standard-inventory-qcow2 adds support
for defining multiple network interface devices in the
provision.fmf file.  This is needed for network tests.
https://pagure.io/fork/rmeggins/standard-test-roles/c/4192f757f610fb6e3570806a282c9b744404ce4e?branch=linux-system-roles
=> test: add another network interface device for qemu tests

tests/tasks/get_modules_and_utils_paths.yml
Some of our tests now run on an ubuntu control node (localhost)
and use `shell` to execute commands there.  Ansible requires
the use of `pipefail`.  The default shell on ubuntu is not
bash and does not have `pipefail`.
=> test: set shell to /bin/bash in order to use pipefail

tests/playbooks/tests_mac_address_match.yml
Some systems do not use the `ethN` interface naming scheme, and
use `ensN` instead.  The test wants to use `eth1` as the second
interface.  If this does not exist, try `ens4` instead.
=> test: find second interface to use for mac address match

tests/ansible.cfg, tests/tasks/create_test_interfaces_with_dhcp.yml
When running tests with a qemu managed node, the dhcp
used by qemu interferes with the dhcp used in the test, which
can cause the test to hang.  Exclude the qemu interfaces from
using the test dhcp.  Note that this only affects the qemu tests -
testing farm and other tests with "real" machines will have a
different mac address - the mac addresses used below are specific
to qemu virtual devices.
Also include a tests/ansible.cfg with a task_timeout=240 to kill
any tasks which take longer than 240 seconds, in case there are
still hangs.  This will cause the test to exit with an error.
=> test: exclude qemu interfaces from dhcp

tests/ensure_provider_tests.py, tests/tests_provider_nm.yml, tests/tests_regression_nm.yml
Support for network-scripts has been removed from Fedora 41
https://discussion.fedoraproject.org/t/f41-change-proposal-removing-network-scripts-package-system-wide/118553
Skip the tests because they fail.
=> test: skip initscript related tests on Fedora 41 and later

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.17.2
=> docs(changelog): version 1.17.2 [citest skip]
