linux-system-roles/network

README.md
Remove POC warning message from the top.
Clarify where NM saves configuration file.
Move Limitations notes to bottom to help users learn to use it faster.
=> Proposed documentation change.

examples/infiniband.yml, library/network_connections.py, library/test_network_connections.py
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1470712
=> add infiniband support

README.md
Please review and add anything if needed, e.g. it might be good to document to what NetworkManager/initscripts settings are the newly documented options translated.
=> Improved documentation, especially of the new options added in 0.4, and DNS.

library/network_connections.py, tests/helpers/ethtool, tests/test_network_connections.py, tests/tests_unit.yml
=> Fix exception on Python3 in _link_read_permaddress() and for sorting network connections

.gitignore, defaults/main.yml, examples/down-profile.yml, examples/remove-profile.yml, tests/ansible_module_network_connections.py, tests/covstats, tests/get-coverage.sh, tests/get-coverage.yml, tests/get-total-coverage.sh, tests/merge-coverage.sh, tests/run-tasks.yml, tests/tasks/assert-device_absent.yml, tests/tasks/assert-device_present.yml, tests/tasks/create-and-remove-interface.yml, tests/tasks/make-profile-absent.yml, tests/tasks/make-profile-down.yml, tests/tasks/manage-test-interface.yml, tests/tasks/show-interfaces.yml, tests/tests_ethernet.yml, tests/tests_helpers-and-asserts.yml
Add more integration tests and scripts to gather coverage data from integration tests
=> More integration tests

library/network_connections.py, tests/remove-profile.yml, tests/tests_ethernet.yml, tests/tests_unit.yml
This demonstrates and fixes #40 
It also contains commits from #50 that should be merged there but are required to create the test case here
=> Detect and fix keyerror

library/network_connections.py, tests/tests_ethernet.yml
This also contains commits from #51 and #50, that are needed here. The new test shows that taking a connection down does not work and suggests a fix. Please comment.
It is also reported in #28
=> Taking a connection down does not work

tests/ensure_non_running_provider.py, tests/tests_bridge_other_provider.yml, tests/tests_default_other_provider.yml, tests/tests_ethernet_other_provider.yml
This makes it easier to figure out what is going on from the logs
=> Tests: Add names for other provider tasks/playbooks

library/network_connections.py
=> [th/nm connection-type] fix creating vlan and mac profiles for NetworkManager

tasks/main.yml
Add two fixes/workarounds in case network.service from initscripts has issues. See commit messages for details.
=> Initscripts workarounds

tasks/main.yml, tests/tasks/assert-device_absent.yml, tests/tasks/assert-device_present.yml, tests/tasks/assert-profile_absent.yml, tests/tasks/assert-profile_present.yml, tests/tasks/get-current_interfaces.yml, tests/tasks/get-interface_stat.yml, tests/tasks/get-profile_stat.yml, tests/tasks/manage-test-interface.yml, tests/tasks/show-interfaces.yml, tests/tests_unit.yml
With these commits, the tests now pass
```
for f in tests/tests_*.yml ; do TEST_DOCKER_EXTRA_ARGS="-it --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro" TEST_SUBJECTS=docker:milcom/centos7-systemd ansible-playbook -i $HOME/standard-test-roles/inventory/standard-inventory-docker  $f &> $f.log & :; done
```
=> More container improvements/cleanups

.travis.yml, defaults/main.yml, meta/main.yml, tests/ensure_non_running_provider.py, tests/tests_bridge_other_provider.yml, tests/tests_default_other_provider.yml, tests/tests_ethernet_other_provider.yml
This is a preparation for #107
=> Cleanup yaml in preparation for molecule testing

library/network_connections.py, tests/playbooks/tests_vlan_mtu.yml, tests/tests_vlan_mtu_initscripts.yml, tests/tests_vlan_mtu_nm.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/116)
=> Revise VLAN MTU test

README.md, library/network_connections.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/131)
=> Add LGTM check

defaults/main.yml, meta/main.yml
This is in preparation for #133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/135)
=> Break long lines in defaults and remove deprecated checks

.travis/config.sh, .travis/custom.sh, .travis/utils.sh, custom_requirements.txt, molecule/default/Dockerfile.j2, molecule/default/molecule.yml, molecule/default/yamllint.yml, pylint_extra_requirements.txt, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/136)
=> Sync some changes from the templates repo

README.md
This fixes #98.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/103)
=> README: Mention mtu option

README.md
Add documentation for existing support for team type until it is configurable
=> Team documentation

tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/network/120)
=> Fix travis coverage

README.md, defaults/main.yml, examples/eth-with-802-1x.yml, library/network_connections.py, module_utils/network_lsr/argument_validator.py, tests/playbooks/tests_802_1x.yml, tests/unit/test_network_connections.py
=> Change 802.1x parameters to be valid python identifiers

.travis/config.sh
Richard Megginson suggested this in
https://github.com/linux-system-roles/network/pull/215#discussion_r420210849
=> travis: Use lsr_check_python_version

tests/playbooks/tests_checkpoint_cleanup.yml
Fix some issues found when working on #219
=> Prepare tests for Fedora 32

README.md, contributing.md
Now the contribution archive has some steps in order to facilitate new
contributors to get in the workflow of the project.
=> Update contributing.md with steps to contributing

contributing.md, library/network_connections.py, tasks/main.yml
Allow to disable the checkpoint feature with a debug flag to make
debugging easier.
=> Library: Introduce debug flags

examples/wireless_wpa_psk.yml
=> Fix wireless WPA PSK example

examples/bond_simple.yml, library/network_connections.py
=> Support creating and activating bond profiles in one run with initscripts

module_utils/network_lsr/utils.py
=> utils: Fix error message format

contributing.md
Signed-off-by: Rafael G. Ruiz <llerrak@hotmail.com>
=> contributing: add DCO requirement

library/network_connections.py, module_utils/network_lsr/argument_validator.py, module_utils/network_lsr/nm_provider.py, scripts/print_all_options.py, tests/unit/test_network_connections.py
=> Update formatting according to new black version

contributing.md
=> Document where to find other images used for testing

tests/ensure_provider_tests.py, tests/tests_802_1x_nm.yml, tests/tests_802_1x_updated_nm.yml, tests/tests_bond_nm.yml, tests/tests_bridge_nm.yml, tests/tests_ethernet_nm.yml, tests/tests_ethtool_features_nm.yml, tests/tests_provider_nm.yml, tests/tests_reapply_nm.yml, tests/tests_states_nm.yml, tests/tests_team_nm.yml, tests/tests_vlan_mtu_nm.yml, tests/tests_wireless_nm.yml
=> Remove workaround for host selection in ensure_provider_tests.py

.travis/config.sh, .travis/runcollection.sh, library/network_connections.py, module_utils/network_lsr/argument_validator.py, module_utils/network_lsr/nm_provider.py, module_utils/network_lsr/utils.py, tox.ini
- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.
=> RHELPLAN-56586 - sync collections related changes from template to network role

.travis/runcollection.sh, tox.ini
Merge: e9f2c3a 4f3c96a
Merge pull request #48 from nhosoi/collections
runcollection.sh - stop passing an argument list
This change allows to eliminate the test argument list as well as the
branch name to retrieve the lsr_role2collection.py script for the
collection test.
=> Sync with template.

tests/tests_unit.yml
=> Disable Python2 unit tests on Fedora

tests/playbooks/integration_pytest_python3.yml, tests/tasks/el_repo_setup.yml, tests/tasks/enable_epel.yml, tests/tasks/setup_802_1x_server.yml, tests/tasks/setup_mock_wifi.yml, tests/tests_802_1x_nm.yml, tests/tests_802_1x_updated_nm.yml, tests/tests_bond_initscripts.yml, tests/tests_bond_nm.yml, tests/tests_bridge_initscripts.yml, tests/tests_bridge_nm.yml, tests/tests_default.yml, tests/tests_default_initscripts.yml, tests/tests_default_nm.yml, tests/tests_ethernet_initscripts.yml, tests/tests_ethernet_nm.yml, tests/tests_ethtool_features_initscripts.yml, tests/tests_ethtool_features_nm.yml, tests/tests_helpers_and_asserts.yml, tests/tests_integration_pytest.yml, tests/tests_provider_nm.yml, tests/tests_reapply_nm.yml, tests/tests_regression_nm.yml, tests/tests_states_initscripts.yml, tests/tests_states_nm.yml, tests/tests_team_nm.yml, tests/tests_unit.yml, tests/tests_vlan_mtu_initscripts.yml, tests/tests_vlan_mtu_nm.yml, tests/tests_wireless_nm.yml
* As EPEL6 has been moved to archive, created `tests/tasks/enable_epel.yml`.
* As CentOS6 has been moved to vault, created `tests/tests_00_setup.yml`.
=> test: Fix EL6 repo

library/network_connections.py, module_utils/network_lsr/nm/__init__.py, module_utils/network_lsr/nm/active_connection.py, module_utils/network_lsr/nm/client.py, module_utils/network_lsr/nm/provider.py
=> Collections - workaround for the module_utils path finding issue in ansible 2.9

module_utils/network_lsr/argument_validator.py
add some code comments about `ArgValidator`
=> [th/arg-validator-doc] argument_validator: add documentation comments

tests/playbooks/tests_eth_dns_support.yml
=> Fixing interface not found failure in tests_eth_dns_support.yml

README.md
=> README: remove "slaves" leftover from documentation

tests/playbooks/tests_bond_deprecated.yml
=> Tests: Use more conscious language

README.md
=> Docs: list all the available dns options for ipv4

README.md
=> Docs: update 'mac' to suggest user using quotation mark

.mdl_style.rb, CHANGELOG.md
=> CHANGELOG: update changelog for 1.3.0 release

.github/workflows/tox.yml
Also run github actions for pushing to get CI updates for changes to the
main branch and a baseline to compare PRs to.
=> Enable github actions for push

.github/workflows/auto-update.yml
Enable https://github.com/tibdex/auto-update to simplify automatic
merging of PRs.
=> Add auto update GitHub action

README.md
=> Document gateway4 and gateway6 setting in README.md

defaults/main.yml
In order to work with ansible-core, json_query is replaced
with selectattr.
=> replace json_query with selectattr

CHANGELOG.md
=> CHANGELOG: update changelog for 1.5.0 release

CHANGELOG.md
=> CHANGELOG: update changelog for 1.6.0 release

README.md
=> [citest skip] README: Clarify the name setting

tests/tests_switch_provider.yml
=> tests: do not run test_switch_provider on CentOS/RHEL 9

CHANGELOG.md
=> CHANGELOG: update changelog for 1.7.0 release

defaults/main.yml
=> add support to Rocky Linux

CHANGELOG.md
=> CHANGELOG: update changelog for 1.7.1 release

.github/run_test.sh
=> [citest skip]Enable more integration tests in GitHub CI

tests/playbooks/tests_bond_options.yml
=> bond: Test infiniband ports in active-backup mode

tests/tasks/create_test_interfaces_with_dhcp.yml
=> Validate the ip addresses added to the DHCP server

CHANGELOG.md
Signed-off-by: Wen Liang <wenliang@redhat.com>
=> CHANGELOG: update changelog for 1.8.0 release

library/network_connections.py
For the active bonding/bridge connection, when all the port connection
profiles are brought down firstly, then the operstate of the controller
device will change into "down" automatically, which denotes missing the
carrier for the controller device. However, the connection for the
controller device should still be considered as active as long as
there is any valid IP address configured.
=> IfcfgUtil: Remediate `connection_seems_active()` for controller

CHANGELOG.md
=> CHANGELOG: update changelog for 1.9.1 release

CHANGELOG.md, README.md, library/network_connections.py, tests/playbooks/tests_auto_gateway.yml
=> [Draft ] Support 'route_metric4' for initscripts provider

CHANGELOG.md
[1.10.1] - 2022-11-14
- none
- none
- support ansible-core-2.14, ansible-lint 6.x
=> Version 1.10.1 - CHANGELOG.md [citest skip]

CHANGELOG.md
[1.11.0] - 2022-12-12
- Support cloned MAC address
- none
- none
=> Version 1.11.0 - CHANGELOG.md [citest skip]

README.md
=> fix the ansible-pull link

.github/CODEOWNERS
=> Github: Add CODEOWNERS

.github/workflows/integration.yml
=> Fix CentOS 7 integration tests

CHANGELOG.md
[1.11.2] - 2023-02-20
- none
- initscripts: Configure output device in routes
- none
=> Version 1.11.2 - CHANGELOG.md [citest skip]

CHANGELOG.md
Create changelog update and release for version 1.11.3
=> docs(changelog): version 1.11.3 [citest skip]

CHANGELOG.md
Create changelog update and release for version 1.11.4
=> docs(changelog): version 1.11.4 [citest skip]

CHANGELOG.md
Create changelog update and release for version 1.12.0
=> docs(changelog): version 1.12.0 [citest skip]

defaults/main.yml
Please add AlmaLinux to the list of distributions recognized as RHEL
=> feat: add AlmaLinux to RHEL compat distro list

CHANGELOG.md
Create changelog update and release for version 1.13.0
=> docs(changelog): version 1.13.0 [citest skip]

CHANGELOG.md
Create changelog update and release for version 1.13.1
=> docs(changelog): version 1.13.1 [citest skip]

README.md
Enhancement:
Updating README.md to reflect some recently added changes or features.
Reason:
README.md is outdated.
Result:
Guarantee that README.md  is up to update.
=> docs: Update README.md [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.13.2
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> docs(changelog): version 1.13.2 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.14.2
=> docs(changelog): version 1.14.2 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.15.1
=> docs(changelog): version 1.15.1 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.15.2
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> docs(changelog): version 1.15.2 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.15.3
=> docs(changelog): version 1.15.3 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.15.4
=> docs(changelog): version 1.15.4 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.15.5
=> docs(changelog): version 1.15.5 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.15.6
=> docs(changelog): version 1.15.6 [citest skip]

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.16.0
=> docs(changelog): version 1.16.0 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.16.2
=> docs(changelog): version 1.16.2 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.16.3
=> docs(changelog): version 1.16.3 [citest skip]

CHANGELOG.md
Update changelog and .README.html for version 1.16.4
=> docs(changelog): version 1.16.4 [citest skip]
